name: maple_py310_ray_osx-64
channels:
  - defaults
dependencies:
  - python=3.10
  - gdal
  - fiona
  - pyshp
  - scikit-image
  - shapely
  - pip=23.3.1
  - pip:
    - tensorflow
    - opencv-python
    - ray[default]
    - pandas==2.1.4
    - pyarrow
