name: maple_py310
channels:
  - defaults
  - apple
dependencies:
  - python=3.10
  - gdal
  - pyshp
  - scikit-image
  - shapely
  - tensorflow-deps
  - pip:
    - opencv-python
    - tensorflow-macos
    - tensorflow-metal
