name: maple_py310_ray
channels:
  - defaults
  - conda-forge
dependencies:
  - gdal
  - fiona
  - pyshp
  - scikit-image
  - shapely
  - pip=23.3.1
  - tensorflow
  - pandas
  - pyarrow
  - requests
  - pip:
    - ray[default]
